backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: "intro"
    label: "Intro"
    folder: "src/content/intro"
    create: false
    slug: "Intro"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "about"
    label: "About"
    folder: "src/content/about"
    create: false
    slug: "About"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "tech"
    label: "Tech"
    folder: "src/content/tech"
    create: false
    slug: "Tech"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "contact"
    label: "Contact"
    folder: "src/content/contact"
    create: false
    slug: "Contact"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "project-card"
    label: "Project cards"
    folder: "src/content/cards"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{card}"
    editor:
      preview: false
    fields:
      - { label: "Project card", name: "display", widget: "boolean" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Developed in...", name: "Developed", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Github link", name: "Github", widget: "string" }
      - { label: "Live link", name: "Live", widget: "string" }
      - { label: "Image of project", name: "Image", widget: "image" }
      - { label: "Fav", name: "fav", widget: "boolean" }
